$dir = "images"
$exts = @("*.jpg","*.jpeg","*.png","*.gif","*.webp","*.bmp","*.JPG","*.JPEG","*.PNG","*.GIF","*.WEBP","*.BMP")

$files = @()
foreach ($ext in $exts) {
    $files += Get-ChildItem -Path $dir -Filter $ext -ErrorAction SilentlyContinue
}

$files = $files | Sort-Object Name -Unique

$lines = @()
$lines += "// Auto-generated by generate-list.bat - do not edit manually"
$lines += "// Run generate-list.bat again after adding images to images/"
$lines += ""
$lines += "const IMAGES = ["
foreach ($f in $files) {
    $lines += "  `"images/$($f.Name)`","
}
$lines += "];"

$lines | Set-Content -Path "images-list.js" -Encoding UTF8

Write-Host "Done: $($files.Count) image(s) written to images-list.js"
