#!/bin/bash
cd "$(dirname "$0")"

echo "images-list.js を生成中..."

dir="images"
exts="jpg jpeg png gif webp bmp JPG JPEG PNG GIF WEBP BMP"

files=()
for ext in $exts; do
    while IFS= read -r f; do
        files+=("$f")
    done < <(find "$dir" -maxdepth 1 -name "*.$ext" 2>/dev/null)
done

# ファイル名でソート・重複除去
IFS=$'\n' sorted=($(printf '%s\n' "${files[@]}" | xargs -I{} basename {} | sort -u))
unset IFS

{
    echo "// Auto-generated by generate-list.sh - do not edit manually"
    echo "// Run generate-list.sh again after adding images to images/"
    echo ""
    echo "const IMAGES = ["
    for name in "${sorted[@]}"; do
        echo "  \"images/${name}\","
    done
    echo "];"
} > images-list.js

echo "Done: ${#sorted[@]} image(s) written to images-list.js"
